#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Global"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it
FNAME="Interpolation"; . ./compile_it
FNAME="Legendre_Utilities"; . ./compile_it
FNAME="Sorting"; . ./compile_it
FNAME="PRNGs"; . ./compile_it
FNAME="Random_Numbers"; . ./compile_it
FNAME="Statistics"; . ./compile_it
#FNAME="Root_Solvers"; . ./compile_it
#FNAME="Gauss_Legendre_w_a"; . ./compile_it
#FNAME="Quadratures"; . ./compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ./compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/atmo/"
FNAME="USSA76"; . ./compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
#FNAME="Particle_Piles"; . ./compile_it
FNAME="cs_Utilities"; . ./compile_it
FNAME="Neutron_Utilities"; . ./compile_it
FNAME="n_Cross_Sections"; . ./compile_it
FNAME="Random_Directions"; . ./compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Setups"; . ./compile_it
FNAME="Atmospheres"; . ./compile_it
FNAME="Satellite_Motion"; . ./compile_it
FNAME="Diverge_approx"; . ./compile_it
#FNAME="Diverge_exact"; . ./compile_it
FNAME="Find_Trajectory"; . ./compile_it
FNAME="Pathlengths"; . ./compile_it
FNAME="Target_Motion"; . ./compile_it
FNAME="Tallies"; . ./compile_it
FNAME="Detectors"; . ./compile_it
FNAME="Neutron_Scatter"; . ./compile_it
FNAME="Sources"; . ./compile_it
FNAME="MC_Neutron"; . ./compile_it
FNAME="Results"; . ./compile_it

# MAIN PROGRAM
SRC_PATH="../source/"
BLD_PATH="../build/"
FNAME="HATS_DRIVER"
echo "Compiling and linking HATS..."
gfortran $GFORT_FLAGS -o ${BLD_PATH}HATS.out ${SRC_PATH}${FNAME}.f90 $OBJ_FILES $LIB_FLAGS
echo "Copying resource files..."
rm -r ${BLD_PATH}Resources
cp -r ../source/resources ${BLD_PATH}Resources
echo "Done."
