#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Legendre_Utilities"; . ./compile_it
