#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="Interpolation"; . ./compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/atmo/"
FNAME="USSA76"; . ./compile_it
