#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Tallies"; . ./compile_it
