#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Global"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it
FNAME="Interpolation"; . ./compile_it
FNAME="Legendre_Utilities"; . ./compile_it
FNAME="Sorting"; . ./compile_it
FNAME="MT2203params"; . ./compile_it
FNAME="PRNGs"; . ./compile_it
FNAME="Random_Numbers"; . ./compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ./compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/atmo/"
FNAME="USSA76"; . ./compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
FNAME="Particle_Piles"; . ./compile_it
FNAME="cs_Utilities"; . ./compile_it
FNAME="Neutron_Utilities"; . ./compile_it
FNAME="n_Cross_Sections"; . ./compile_it
FNAME="Random_Directions"; . ./compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Setups"; . ./compile_it
FNAME="Atmospheres"; . ./compile_it
FNAME="Satellite_Motion"; . ./compile_it
FNAME="Diverge_approx"; . ./compile_it
FNAME="Find_Trajectory"; . ./compile_it
FNAME="Pathlengths"; . ./compile_it
FNAME="Target_Motion"; . ./compile_it
FNAME="Tallies"; . ./compile_it
FNAME="Detectors"; . ./compile_it
FNAME="Neutron_Scatter"; . ./compile_it
FNAME="Sources"; . ./compile_it
FNAME="MC_Neutron"; . ./compile_it
