#!/bin/sh
echo "Compiling ${FNAME}..."
# compile the file
$COMP_NAME $GFORT_FLAGS_o -o ${OBJ_DIR}${FNAME}.o ${SRC_PATH}${FNAME}.f90 $LIB_FLAGS

# add the name of the object file to the list
OBJ_FILES="${OBJ_FILES} ${OBJ_DIR}${FNAME}.o"
