#!/bin/sh
$COMP_NAME --version
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"
echo "Linker Flags:"
echo "  $LINK_FLAGS"
echo "Objects emitted to $OBJ_DIR"
echo "Run application (if built) with:  $RUN_CMD ..."