#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it
FNAME="PRNGs"; . ./compile_it
FNAME="Random_Numbers"; . ./compile_it

#TEST PROGRAM
SRC_PATH="../testing/PRNGs/"
BLD_PATH="../build/"
FNAME="testPRNGmt2203"
echo "Compiling and linking testPRNGs..."
gfortran $GFORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES
echo "Copying resource files..."
rm -fr ${SRC_PATH}Resources
cp -r ../source/resources ${SRC_PATH}Resources

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
./${FNAME}${EXT}