#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Global"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it
FNAME="Interpolation"; . ./compile_it
FNAME="Legendre_Utilities"; . ./compile_it
FNAME="Sorting"; . ./compile_it
FNAME="PRNGs"; . ./compile_it
FNAME="Random_Numbers"; . ./compile_it
FNAME="Statistics"; . ./compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/atmo/"
FNAME="USSA76"; . ./compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ./compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
FNAME="cs_Utilities"; . ./compile_it
FNAME="Neutron_Utilities"; . ./compile_it
FNAME="n_Cross_Sections"; . ./compile_it
FNAME="Random_Directions"; . ./compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Atmospheres"; . ./compile_it
FNAME="Target_Motion"; . ./compile_it
FNAME="Neutron_Scatter"; . ./compile_it
FNAME="Satellite_Motion"; . ./compile_it
FNAME="Find_Trajectory"; . ./compile_it
FNAME="Diverge_approx"; . ./compile_it
FNAME="Tallies"; . ./compile_it
FNAME="Detectors"; . ./compile_it

#TEST PROGRAM
SRC_PATH="../testing/prevTrajectory/"
FNAME="LPadjoint_raw"
echo "Compiling and linking LPadjoint..."
$COMP_NAME $GFORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
${RUN_CMD}${FNAME}${EXT}
