#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Global"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it
FNAME="Root_Solvers"; . ./compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ./compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
FNAME="Neutron_Utilities"; . ./compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Satellite_Motion"; . ./compile_it
FNAME="Find_Trajectory"; . ./compile_it
FNAME="Diverge_approx"; . ./compile_it

#TEST PROGRAM
SRC_PATH="../testing/prevTrajectory/"
BLD_PATH="../build/"
FNAME="testPrevTrajectory"
echo "Compiling and linking testPrevTrajectory..."
$COMP_NAME $GFORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
${RUN_CMD}${FNAME}${EXT}
