#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="FileIO_Utilities"; . ./compile_it

#TEST PROGRAM
SRC_PATH="../source/tests/"
BLD_PATH="../build/"
FNAME="testCR"
echo "Compiling and linking testCR..."
gfortran $GFORT_FLAGS -o ${SRC_PATH}${FNAME}.out ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
./${FNAME}.out