#!/bin/sh

# CLEAN OLD BUILD FILES
./clean

# SET COMPILER FLAGS
. ./set_flags
. ./echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ./compile_it
FNAME="Global"; . ./compile_it
FNAME="Utilities"; . ./compile_it
FNAME="Interpolation"; . ./compile_it
FNAME="Gauss_Legendre_w_a"; . ./compile_it
FNAME="Quadratures"; . ./compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/atmo/"
FNAME="USSA76"; . ./compile_it

#TEST PROGRAM
SRC_PATH="../testing/EPLquads/"
BLD_PATH="../build/"
FNAME="EPLquadpoints"
echo "Compiling and linking EPLquadpoints..."
gfortran $GFORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
./${FNAME}${EXT}
